<?php
namespace xxAROX\Verify;
use pocketmine\command\Command;
use pocketmine\command\CommandSender;
use pocketmine\event\Listener;
use pocketmine\Player;
use pocketmine\plugin\PluginBase;
use xxAROX\Verify\Verify;

/**
 * Class VerifyMain
 * @package xxAROX\Verify
 */
class VerifyMain extends PluginBase implements Listener {
    public function onEnable()
    {
        $this->getServer()->getPluginManager()->registerEvents($this, $this);
\xxAROX\Verify\Verify::init();
    }

    public function onCommand(CommandSender $sender, Command $command, string $label, array $args): bool
    {
        if ($command->getName() === "verify" && $sender instanceof Player) {
            Verify::activateVerifyCode($sender);
            return true;
        }
        return parent::onCommand($sender, $command, $label, $args); // TODO: Change the autogenerated stub
    }

}
